{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: nccl-host-{{ $i }}
spec:
  selector:
    app: nccl-host-{{ $i }}
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: nccl-test-host-{{ $i }}
  labels:
    app: nccl-host-{{ $i }}
spec:
  hostname: host{{ $i }}
  subdomain: nccl-host-{{ $i }}
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: tcpxo-daemon
      image: {{ .Values.image.tcpxoDaemon }}
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -ex
          chmod 755 /fts/entrypoint_rxdm_container.sh
          /fts/entrypoint_rxdm_container.sh --num_hops=2 --num_nics=8 --uid= --alsologtostderr
      securityContext:
        privileged: true
      volumeMounts:
        - name: nvidia-install-dir-host
          mountPath: /usr/local/nvidia
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
    - name: nccl-test
      image: {{ .Values.image.ncclTest }}
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - |
          cat >/scripts/allgather.sh <<EOF
          #!/bin/bash
          /scripts/init_ssh.sh \${@};
          pushd /scripts;
          /scripts/gen_hostfiles.sh \${@};
          popd;
          BENCHMARK=all_gather_perf NHOSTS=2 NCCL_LIB_DIR="${LD_LIBRARY_PATH}" LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" /scripts/demo-run-nccl-test-tcpxo-via-mpi.sh
          EOF
          chmod +x /scripts/allgather.sh
          service ssh restart;
          sleep infinity;
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      securityContext:
        privileged: true
      volumeMounts:
        - name: shared-memory
          mountPath: /dev/shm
      resources:
        limits:
          nvidia.com/gpu: {{ .Values.resources.limits.nvidia.com/gpu }}
  volumes:
    - name: nvidia-install-dir-host
      hostPath:
        path: {{ .Values.volumes.nvidiaInstallDirHost.path }}
    - name: shared-memory
      emptyDir:
        medium: {{ .Values.volumes.sharedMemory.medium }}
        sizeLimit: {{ .Values.volumes.sharedMemory.sizeLimit }}
{{- end }}
